# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1363274724);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1363274846);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1363277539);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1363263019);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 8);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20130307122433");
user_pref("browser.startup.homepage_override.mstone", "19.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":0,\"passwords\":0}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 10);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"1.11.2\",\"type\":\"extension\",\"descriptor\":\"/home/ilu/.mozilla/firefox/s8attuf1.default/extensions/firebug@software.joehewitt.com.xpi\"},\"webapps-team@lists.launchpad.net\":{\"version\":\"2.4.1\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2012.10.12.beta,ubufox%40ubuntu.com:2.6,langpack-en-ZA%40firefox.mozilla.org:19.0.2,globalmenu%40ubuntu.com:3.7.2,langpack-en-GB%40firefox.mozilla.org:19.0.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:19.0.2");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.11.2");
user_pref("extensions.firebug.previousPlacement", 3);
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1362637019000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1350485973000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1362637167000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1362670430000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1362842818000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1362842814000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1362670430000}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"/home/ilu/.mozilla/firefox/s8attuf1.default/extensions/firebug@software.joehewitt.com.xpi\",\"mtime\":1362713296000}}}]");
user_pref("extensions.lastAppVersion", "19.0.2");
user_pref("extensions.lastPlatformVersion", "19.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/firebug");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20130307122433");
user_pref("gecko.mstone", "19.0.2");
user_pref("idle.lastDailyNotification", 1363266623);
user_pref("intl.charsetmenu.browser.cache", "windows-1251, windows-1254, windows-1252, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.database", "{\"files\":[{\"fingerprint\":\"fd216087fb85d015f0c8844b77885d\",\"exists\":true,\"page\":4,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":671},{\"fingerprint\":\"372799de3c9d7d43b2c28ff39042bf0\",\"exists\":true,\"page\":24,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":433},{\"fingerprint\":\"6e33bfc3b03fc16f36f2e241924f62a3\",\"exists\":true,\"page\":11,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":505},{\"fingerprint\":\"73e25f9bfa146221e379f6191807a90\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":792},{\"fingerprint\":\"9e21f941539f295881d694c93701446\",\"exists\":true,\"page\":3,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":670},{\"fingerprint\":\"b5193e42f0136b489d6aba3ed6a17d52\",\"exists\":true,\"page\":3,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":359},{\"fingerprint\":\"733c2a896a9526d11be9b36b84fb1da\",\"exists\":true,\"page\":4,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":54},{\"fingerprint\":\"8cd522ceb1b833b2ded47efd8d7df90\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":849},{\"fingerprint\":\"3f8a71bcacfe304baab61cce2bd5a8f\",\"exists\":true,\"page\":13,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":639},{\"fingerprint\":\"903a5bb0dbcd6dd853697146b312278\",\"exists\":true,\"page\":278,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":785},{\"fingerprint\":\"ece4c1cfe8415d44718e3aeb7972dc37\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":792}]}");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1362842012);
user_pref("places.history.expiration.transient_current_max_pages", 103400);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 2);
user_pref("spellchecker.dictionary", "en_GB");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1362842012);
user_pref("toolkit.startup.last_success", 1363312139);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1364712684);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
