#!/usr/bin/env bash

if [[ -s "/home/ilu/.rvm/environments/ruby-2.0.0-p0" ]]
then
  source "/home/ilu/.rvm/environments/ruby-2.0.0-p0"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ilu/.rvm/environments/ruby-2.0.0-p0'" >&2
  exit 1
fi
