#!/usr/bin/env bash

if [[ -s "/home/ilu/.rvm/environments/ruby-2.0.0-p0@global" ]]
then
  source "/home/ilu/.rvm/environments/ruby-2.0.0-p0@global"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ilu/.rvm/environments/ruby-2.0.0-p0@global'" >&2
  exit 1
fi
