# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "edsintegration%40mozilla.com:0.5,globalmenu%40ubuntu.com:3.6.4,messagingmenu%40mozilla.com:1.3.1,langpack-en-GB%40thunderbird.mozilla.org:17.0.3,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1361443676000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1362119980000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/globalmenu@ubuntu.com\",\"mtime\":1362119977000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1361443676000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"mtime\":1361444112000}}}]");
user_pref("extensions.lastAppVersion", "17.0.3");
user_pref("extensions.lastPlatformVersion", "17.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "0230463e-41a8-4470-ad2d-251cb67b783");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
